Try to fix failing Selenium containers

diff --git a/.github/workflows/moodle-plugin-ci.yml b/.github/workflows/moodle-plugin-ci.yml
--- a/.github/workflows/moodle-plugin-ci.yml
+++ b/.github/workflows/moodle-plugin-ci.yml
@@ -114,7 +114,21 @@ jobs:
       - name: Behat features
         id: behat
         if: ${{ !cancelled() }}
-        run: moodle-plugin-ci behat --profile chrome --suite boost_union
+        run: |
+          ATTEMPTS=3
+          COUNT=0
+          until [ $COUNT -ge $ATTEMPTS ]
+          do
+            moodle-plugin-ci behat --profile chrome --suite boost_union && break
+            COUNT=$((COUNT+1))
+            echo "Behat failed and the Selenium container might be broken down. Will retry full restart of Behat (retry $COUNT of $ATTEMPTS)"
+            sleep 10
+          done
+
+          if [ $COUNT -eq $ATTEMPTS ]; then
+            echo "Behat failed finally after $ATTEMPTS attempts"
+            exit 1
+          fi
 
       - name: Upload Behat Faildump
         if: ${{ failure() && steps.behat.outcome == 'failure' }}
